services:
  postgres:
    image: postgres:16
    container_name: netBanking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netBankingDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redisDb
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

#  backend:
#    image: dockerkartikeya/acid-compliant-transaction-engine:v1
#    container_name: netBanking-backend
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env  # <--- This automatically injects ALL variables from your .env file
#    environment:
#      # If your application.properties expects SPRING_DATASOURCE_URL, map it to the .env variables here:
#      SPRING_DATASOURCE_URL: ${DB_URL}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
#      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
#    depends_on:
#      - postgres
#      - redis
#    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: